apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    section: intro
spec:
  # modify replicas according to your case
  replicas: 15
  # strategy -- 
  selector:
    matchLabels: #<- Must match labels of Pod
      app: sample 
  template:
  # pod definition
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
      - name: app
        image: abdennour/sample-app:blue # v1, v2, blue, green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector: # <-- mapped to labels of Pods
    app: sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # <--- mapped to containerPort of Pod
---
  apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: sample-ingress
    annotations:
      kubernetes.io/ingress.class: nginx
  spec:
    rules:
    - host: sample.vemessage.com
      http:
        paths:
        - backend:
            serviceName: sample-service
            servicePort: 80